### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by Jogistar** [JeromeHXP/ondilo#2]
Hi @JeromeHXP 
Any chance this project could be ported to work with homebridge.. I would love to help the best I can.

Sincerly 
Jogistar

**Comment by JeromeHXP** [comment]
Hi @Jogistar ,
This is just a python library to ease access to Ondilo's REST APIs. So it can be used in any system you want.
I don't know anything about Homebridge so I won't be able to help you there.
Regards

**Comment by Jogistar** [comment]
> Hi @Jogistar , This is just a python library to ease access to Ondilo's REST APIs. So it can be used in any system you want. I don't know anything about Homebridge so I won't be able to help you there. Regards

Ok.. 👍😎
