### ISSUE TITLE
Not working anymore after upgrade to 2023.12

### ISSUE THREAD

**Issue by chheiss** [JeromeHXP/ondilo#5]
Hi! The integration is not working anymore after the home assistant upgrade to 2023.12.

Any ideas on this?

Chris

**Comment by storebatfar** [comment]
Same issue here. If trying to a fresh setup, the page shows ssl error.

**Comment by StewartM30** [comment]
Same here.

**Comment by JeromeHXP** [comment]
It was (again) an issue on their SSL cert.
